### ISSUE TITLE
Appendix B.2: Add TXP sub-case and clarify "OCh-CC" (adjacency) changes

### ISSUE THREAD

**Issue by ggalimba56** [IETF-TEAS-WG/actn-poi#29]
To be clarified how the LAG and Non LAG cases will change in case to TXP connections and in chase of different MXP client port change due to failures.
I'll propose some text to explain.

**Comment by italobusi** [comment]
**[2022-09-27 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-09-27.md)**

Basically means to put some sentences to explain that for TXP sub-case OCh-CC is straightforward while for MXP this is bit more complicated but still can be managed.

- [ ]  @**ggalimba56** will submit a text proposal to be reviewed by all.

**Comment by ggalimba56** [comment]
The end to end Client circuit provisioning between two TXPs is relative clear and its implementation is simple.
There is a one to one relationship between the TXP client port and the TXP trunk port. The client port bitrate determines the Trunk (or DWDM) port bit rate. The bit rate parameters will determine the Baud-rate, the modulation forma, the FEC etc.
The controller, to set a TXP Client connection, needs to fine a DWDM circuit suitable to comply the DWDM port parameters.
Different is when the Client connection is using a Muxponder port (e.g. 10GE).  In the MXP configuration there is a one to many relationship between the MXP DWDM port (Trunk) and the client ports, foe example there might be a 100Gb/s trunk port shared by then 100GE client ports.   The controller asked to set a 10GE Client connection between two MXP ports needs then to check whether there already is a DWDM connection (or OTSi) between the two MXP and then take actions:
1) if there is the OTSi connection then the controller needs only to enable the 10GE client ports (matching the number or assigning to them a proper time slot into the OTSi) and espablish the 10GE connection.  It needs to be noted that in MXPs usually the client ports are assigned to the time slots by default (or by design).
2) if there is NOT an OTSi connection between the two MXP the controller has to first establish the DWDM connection finding a proper circuit matching the Trunk transceiver optical parameters (e.g. OTSi carrying a OTU4).  Once the circuit is established the controller can enable the 100GE client ports and set the 10GE end to end service.

**Comment by italobusi** [comment]
**[2022-11-22 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-11-22.md)**

> [ ] @italobusi Update the appendices as agreed and incorporate the text proposed by Gabriele in appendix A.3

To be done in the next editorial update

> * [ ]  @jbouqui153 @FabioPeruzzini  check whether it is worthwhile analyzing the muxponder scenario in this document or in a future document

Jeff: we should consider both transponder and muxponder scenarios.

Daniele: what would be the significant changes from transponder and muxponder?

Italo: the workflow would be different since there will be a N:1 relationship between the IP Links and the underlay Optical Tunnels

Check if it is enough just to mention that the analysis can also apply to the muxponder case but that in that case the workflow would be different since there a relationship between the IP Links and the underlay Optical Tunnels

In the appendix we can explain in more details the differences in the workflows
